# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180115_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatevideopage',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatevideopage',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatevideopage',
            name='vote_views',
            field=models.IntegerField(default=0),
        ),
    ]
