# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180430_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopage',
            name='category',
            field=models.CharField(choices=[(b'LESSON', 'LESSON'), (b'DEMONSTRATION', 'DEMONSTRATION'), (b'EXPERIMENT', 'EXPERIMENT'), (b'PROBLEM_SOLVING', 'PROBLEM_SOLVING'), (b'ADVANCED', 'ADVANCED'), (b'OTHER', 'OTHER'), (b'READING', 'READING')], default=b'LESSON', max_length=40),
        ),
    ]
