# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_candidatevideopage_playing_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatevideopage',
            name='youtube_channel_id',
            field=models.CharField(default='EMPTY', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videopage',
            name='youtube_channel_id',
            field=models.CharField(default='EMPTY', max_length=25),
            preserve_default=False,
        ),
    ]
