# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 19:43
from __future__ import unicode_literals

from django.db import migrations, transaction

from common.utils import request_youtube_info


def load_videopages(apps, schema_editor):
    VideoPage = apps.get_model('core', 'VideoPage')
    load_youtube_data(VideoPage)


def load_candidates(apps, schema_editor):
    CandidateVideoPage = apps.get_model('core', 'CandidateVideoPage')
    load_youtube_data(CandidateVideoPage)


def load_youtube_data(model):
    empty_videos = model.objects.count()
    print ""
    print "Videos count", empty_videos
    for offset in range(0, empty_videos, 20):
        print 100.0 * offset / empty_videos
        videos = model.objects.order_by('id')[offset:offset + 20]
        videos_by_id = {video.youtube_movie_id:video for video in videos if video.youtube_channel_id == 'EMPTY'}
        response = request_youtube_info(video_id=','.join(videos_by_id.keys()), part='snippet')
        if 'items' in response and len(response['items']) > 0:
            for youtube_info in response['items']:
                video = videos_by_id[youtube_info['id']]
                video.youtube_channel_id = youtube_info['snippet']['channelId']
                video.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_auto_20181126_2013'),
    ]

    operations = [
        migrations.RunPython(load_videopages, lambda x, y: True),
        migrations.RunPython(load_candidates, lambda x, y: True)
    ]
